### ISSUE TITLE
"steal" syntax not working in grunt build

### ISSUE THREAD

**Issue by jawshooah** [bitovi/steal#307]
I'm currently considering migrating from legacy StealJS (3.3.0pre) to the current version, but all of my existing code uses the old `steal("moduleA", "moduleB", function(A, B) { ... })` syntax. So naturally, I was excited when I saw that, supposedly, [this syntax is still supported](http://stealjs.com/docs/syntax.steal.html).

I used the Quick Start guide to create a test page, and `grunt build` went fine using the provided ES6 syntax. But then I tried steal syntax:
```js
steal('bower_components/jquery/dist/jquery.js', function($) {
    $(document.body).append("<h1>Hello World!</h1>");
});
```
And I got this:
```bash
Running "stealBuild:default" (stealBuild) task
OPENING: main
steal.js INFO: app loaded successfully
error [TypeError: Error loading "bower_components/jquery/dist/jquery" at file:/Users/joshuahagins/dev/sentrana/steal-test/bower_components/jquery/dist/jquery.js
Error loading "bower_components/jquery/dist/jquery" from "main" at file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Error evaluating file:/Users/joshuahagins/dev/sentrana/steal-test/bower_components/jquery/dist/jquery.js
Cannot call method 'createElement' of undefined] TypeError: Error loading "bower_components/jquery/dist/jquery" at file:/Users/joshuahagins/dev/sentrana/steal-test/bower_components/jquery/dist/jquery.js
Error loading "bower_components/jquery/dist/jquery" from "main" at file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Error evaluating file:/Users/joshuahagins/dev/sentrana/steal-test/bower_components/jquery/dist/jquery.js
Cannot call method 'createElement' of undefined
    at assert (evalmachine.<anonymous>:887:21)
    at evalmachine.<anonymous>:2555:24
    at evalmachine.<anonymous>:2606:3
    at evalmachine.<anonymous>:34:3
    at evalmachine.<anonymous>:38:2
    at doEval (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1940:10)
    at __eval (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1839:7)
    at Loader.exec [as __exec] (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:212:5)
    at Loader.loader.instantiate (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1385:16)
    at Loader.loader.instantiate (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1706:32)
ERROR: Cannot read property 'order' of undefined TypeError: Cannot read property 'order' of undefined
    at visit (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:7:12)
    at /Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:11:5
    at Array.forEach (native)
    at visit (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:10:22)
    at module.exports (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:16:2)
    at /Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/build/multi.js:119:4
    at Array.forEach (native)
    at /Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/build/multi.js:118:9
    at eval (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1621:100)
    at promiseHandle (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1715:20)
```
Is this syntax no longer supported?

**Comment by matthewp** [comment]
jquery is incorrectly detected as an AMD module when it's actually a global. In your config do:

System.meta.jquery = { format: "global" };

**Comment by justinbmeyer** [comment]
You have to configure jQuery as a global.

**Comment by jawshooah** [comment]
Ah, I see. Will I have to do the same for all library dependencies?

**Comment by justinbmeyer** [comment]
No, only UMD ones.

**Comment by jawshooah** [comment]
Cool, much appreciated.
