### ISSUE TITLE
Cannot call method 'then' of undefined

### ISSUE THREAD

**Issue by jawshooah** [bitovi/steal#308]
Following up on #307, I decided to try the `steal(...).then(...)` syntax, since I use it in a lot of places in my legacy code. Here's `main.js`:
```js
steal('jquery').then('can', function() {
    $(document.body).append("<h1>Hello World!</h1>");
});
```
and `stealconfig.js`:
```js
System.config({
    paths: {
        "jquery/jquery": "bower_components/jquery/dist/jquery.js",
        "can/can": "bower_components/canjs/can.jquery.js"
    },
    meta: {
        "jquery/jquery": {
            format: "global"
        }
    }
});
```
...and here's the result:
```bash
$ grunt build
Running "stealBuild:default" (stealBuild) task
OPENING: main
steal.js INFO: app loaded successfully
error [TypeError: Error loading "main" at file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Error evaluating file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Cannot call method 'then' of undefined] TypeError: Error loading "main" at file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Error evaluating file:/Users/joshuahagins/dev/sentrana/steal-test/main.js
Cannot call method 'then' of undefined
    at evalmachine.<anonymous>:1:17
    at doEval (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1940:10)
    at __eval (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:1839:7)
    at Loader.exec [as __exec] (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/dist/system.src.js:212:5)
    at Loader.loader.instantiate (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/main.js:642:14)
    at Loader.System.instantiate (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/trace.js:95:31)
    at p.then.then.then.load.address (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/steal/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:277:31)
    at eval (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1621:100)
    at promiseHandle (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1715:20)
    at eval (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1709:9)
ERROR: Cannot read property 'order' of undefined TypeError: Cannot read property 'order' of undefined
    at visit (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:7:12)
    at module.exports (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/graph/order.js:16:2)
    at /Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/build/multi.js:119:4
    at Array.forEach (native)
    at /Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/lib/build/multi.js:118:9
    at eval (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1621:100)
    at promiseHandle (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1715:20)
    at eval (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1709:9)
    at flush (eval at <anonymous> (/Users/joshuahagins/dev/sentrana/steal-test/node_modules/steal-tools/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:1510:7)
    at process._tickCallback (node.js:442:13)
```
Is this syntax no longer supported? If not, how can I guarantee the order in which modules are loaded?

**Comment by matthewp** [comment]
`.then` is no longer supported. Order of dependencies shouldn't matter. Each module should list its own dependencies. If any module fails to list a dependency (this happens for jquery plugins often) you can fix it in the config with meta deps:

```js
System.config({
  meta: {
    'jquery-cookie': {
      deps: ['jquery']
    }
  }
});
```

In the example you gave, `can` has `jquery` as a dependency already, so you don't need to do that anyways.
